language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.2.3
  - jruby-19mode
before_install: gem install bundler -v 1.11.2
services:
  - redis-server
jruby_before_script:
  - bundle exec jbundle install
